name: Wiki

on: [ workflow_dispatch ]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    if: ${{ success() }}	
    steps:
    - name: The job has failed
      run: >
       curl -X PATCH
       -d '{"title":"sdfasd"}' 
       https://api.github.com/repos/funsimator/Autorentool/issues/2 	    