name: Wiki

on: [ workflow_dispatch ]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          title: "Workflow failed"
          body: |
            ### Run Failed
            - Workflow name:${{  github.workflow }}
            - Gestartet von ${{ github.actor }}
            - Genauere Infomationen zu dem Run hier:
            - https://github.com/funsimator/Autorentool/actions/runs/${{ github.run_id }}
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}		  