name: Wiki

on: [ workflow_dispatch ]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    if: ${{ success() }}	
    steps:
    - name: Wiki API
      run: >
       curl -X PATCH
       -H "Authorization: token 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"
       -d '{"title":"sdfasd"}' 
       https://api.github.com/repos/funsimator/Autorentool/issues/2 	    